
import { Area, StudyStatus } from './types';

export interface HotTopic {
  name: string;
  area: string;
  category: 'Clínica Médica' | 'Cirurgia Geral' | 'Ginecologia e Obstetrícia' | 'Pediatria' | 'Medicina Preventiva';
  observations?: string;
}

export const HOT_TOPICS_LIST: HotTopic[] = [
  // CLÍNICA MÉDICA
  { name: "Hipertensão arterial", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Insuficiência cardíaca", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Infarto agudo do miocárdio", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Cefaleia", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Terapia antitrombótica – CHA2DS2-VASc", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Doenças da placa (miastenia gravis, Eaton-Lambert)", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Tireoide (hiper/hipo/nódulos)", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Artrites e espondilites", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "Obesidade", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Malária", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Diabetes mellitus", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Mecanismo medicamentoso (furosemida)", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Hemorragia digestiva alta", area: "Gastroenterologia", category: 'Clínica Médica' },
  { name: "Asma", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "Cirrose alcoólica descompensada", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Glomerulopatias", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Síndrome da fragilidade no idoso (Fried)", area: "Geriatria", category: 'Clínica Médica' },
  { name: "Lúpus eritematoso sistêmico", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "Transfusão de hemocomponentes", area: "Hematologia", category: 'Clínica Médica' },
  { name: "DPOC (vacinas, manejo)", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "HIV/AIDS e doenças oportunistas", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Tuberculose", area: "Infectologia/Pneumo", category: 'Clínica Médica' },
  { name: "Sepse", area: "Infectologia/Terapia Intensiva", category: 'Clínica Médica' },
  { name: "Trombopatias (trombofilia, trombocitemia)", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Intoxicação por metanol", area: "Toxicologia", category: 'Clínica Médica' },
  { name: "Leucemias mieloide e linfocítica", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Nefrolitíase", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Neutropenia febril e lise tumoral", area: "Hematologia/Onco", category: 'Clínica Médica' },
  { name: "Lesão renal aguda", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Hepatites", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Hemorragia subaracnoidea", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Doença inflamatória intestinal", area: "Gastroenterologia", category: 'Clínica Médica' },
  { name: "Epilepsia", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Febre reumática", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "AVC", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Endocardite – critérios de Duke", area: "Infectologia/Cardio", category: 'Clínica Médica' },
  { name: "Psiquiatria (ideação suicida, delírio)", area: "Psiquiatria", category: 'Clínica Médica' },
  { name: "Síndrome do choque tóxico", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Efeitos adversos – haloperidol", area: "Psiquiatria/Neuro", category: 'Clínica Médica' },
  { name: "Choques (cardio, hipovol, misto, neuro)", area: "Terapia Intensiva", category: 'Clínica Médica' },
  { name: "Hanseníase", area: "Infectologia/Dermato", category: 'Clínica Médica' },
  { name: "Esclerose sistêmica", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "Neuropatias (ELA, Guillain-Barré, EM)", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Lombalgia e radiculopatias", area: "Neurologia/Reumato", category: 'Clínica Médica' },
  { name: "Nódulos hepáticos", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Esteatose hepática", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Disfagia aguda (DRGE, acalásia, esofagite)", area: "Gastroenterologia", category: 'Clínica Médica' },
  { name: "Hemofilias", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Anemias", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Dengue e arboviroses", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Esporotricose e escabiose", area: "Dermatologia", category: 'Clínica Médica' },
  { name: "Leishmaniose", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Pneumonia", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "Doenças hipofisárias", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Análise de líquidos (pleural, ascítico)", area: "Geral", category: 'Clínica Médica' },
  { name: "Linfomas", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Fibrilação atrial", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Doença renal crônica", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Distúrbios hidroeletrolíticos e ECG", area: "Nefrologia/Cardio", category: 'Clínica Médica' },

  // CIRURGIA GERAL
  { name: "Apendicite aguda", area: "Abdome Agudo", category: 'Cirurgia Geral' },
  { name: "Nefrolitíase (cirúrgico)", area: "Urologia", category: 'Cirurgia Geral' },
  { name: "Diverticulite e diverticulose", area: "Coloproctologia", category: 'Cirurgia Geral' },
  { name: "Abdome agudo em crianças", area: "Pediatria Cirúrgica", category: 'Cirurgia Geral' },
  { name: "Colelitíase, colecistite, colangite", area: "Vias Biliares", category: 'Cirurgia Geral' },
  { name: "Nódulos hepáticos (cirúrgico)", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Hemorragia digestiva alta (cirúrgico)", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Câncer de próstata", area: "Urologia", category: 'Cirurgia Geral' },
  { name: "Hemorragia digestiva baixa", area: "Coloproctologia", category: 'Cirurgia Geral' },
  { name: "Drenagem e análise de líquido pleural", area: "Tórax", category: 'Cirurgia Geral' },
  { name: "Pancreatite aguda e crônica", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Profilaxia de TEV", area: "Vascular", category: 'Cirurgia Geral' },
  { name: "Hérnias", area: "Parede Abdominal", category: 'Cirurgia Geral' },
  { name: "Cisto tireoglosso e cervical", area: "Cabeça e Pescoço", category: 'Cirurgia Geral' },
  { name: "Doenças orificiais", area: "Coloproctologia", category: 'Cirurgia Geral' },
  { name: "DRGE (cirúrgico)", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Torção ovariana", area: "Ginecologia Cirúrgica", category: 'Cirurgia Geral' },
  { name: "Tamponamento cardíaco", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "ATLS", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "Resposta metabólica ao trauma (REMIT)", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Abdome agudo obstrutivo", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Procedimentos (AVC, cantoplastia, drenagem)", area: "Técnica Cirúrgica", category: 'Cirurgia Geral' },
  { name: "Grandes queimados", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Tumor de pâncreas e vias biliares", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Abdome agudo isquêmico", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Doença inflamatória intestinal (cirúrgico)", area: "Coloproctologia", category: 'Cirurgia Geral' },
  { name: "Úlceras de pressão", area: "Plástica", category: 'Cirurgia Geral' },
  { name: "Trombose venosa profunda e úlceras", area: "Vascular", category: 'Cirurgia Geral' },
  { name: "Pneumotórax e hemotórax", area: "Tórax/Trauma", category: 'Cirurgia Geral' },
  { name: "Urgências urológicas", area: "Urologia", category: 'Cirurgia Geral' },
  { name: "Protocolo de transfusão maciça", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "Câncer de esôfago, estômago e cólon", area: "Geral", category: 'Cirurgia Geral' },

  // GINECOLOGIA E OBSTETRÍCIA
  { name: "Anticoncepção", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Miomatose uterina", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Ciclo menstrual", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Manejo da vítima de violência sexual", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Hiperplasia e atrofia endometrial", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Úlceras genitais", area: "IST", category: 'Ginecologia e Obstetrícia' },
  { name: "Sangramento uterino anormal", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "ISTs: HIV, sífilis, herpes", area: "IST", category: 'Ginecologia e Obstetrícia' },
  { name: "Corrimentos vaginais", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Endometriose", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Pólipos endometriais", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Câncer de mama – BI-RADS", area: "Mastologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Seguimento da gestante e ISTs", area: "Pré-natal", category: 'Ginecologia e Obstetrícia' },
  { name: "Análise de Doppler", area: "Vitalidade Fetal", category: 'Ginecologia e Obstetrícia' },
  { name: "Toxoplasmose gestacional – seguimento", area: "Pré-natal", category: 'Ginecologia e Obstetrícia' },
  { name: "Aloimunização", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sífilis na gestação – seguimento", area: "Pré-natal", category: 'Ginecologia e Obstetrícia' },
  { name: "Hemorragia pós-parto", area: "Parto", category: 'Ginecologia e Obstetrícia' },
  { name: "Alterações no líquido amniótico", area: "Vitalidade Fetal", category: 'Ginecologia e Obstetrícia' },
  { name: "Gestante com tuberculose, malária, dengue", area: "Patologia Obstétrica", category: 'Ginecologia e Obstetrícia' },
  { name: "Sinais de gravidez", area: "Diagnóstico", category: 'Ginecologia e Obstetrícia' },
  { name: "HPV", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Doença hipertensiva da gestação", area: "Patologia Obstétrica", category: 'Ginecologia e Obstetrícia' },
  { name: "Hiperêmese gravídica", area: "Patologia Obstétrica", category: 'Ginecologia e Obstetrícia' },
  { name: "Diabetes gestacional", area: "Patologia Obstétrica", category: 'Ginecologia e Obstetrícia' },
  { name: "Pré-natal", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sangramento do 1º trimestre", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Doença trofoblástica gestacional", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sangramento do 2º trimestre", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Gestante com anemia", area: "Patologia Obstétrica", category: 'Ginecologia e Obstetrícia' },
  { name: "Gravidez ectópica", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Trabalho de parto – fases e períodos", area: "Parto", category: 'Ginecologia e Obstetrícia' },
  { name: "Partograma", area: "Parto", category: 'Ginecologia e Obstetrícia' },
  { name: "Abdome agudo obstétrico/ginecológico", area: "Urgência", category: 'Ginecologia e Obstetrícia' },
  { name: "Distócias", area: "Parto", category: 'Ginecologia e Obstetrícia' },
  { name: "Embriogênese", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Menopausa", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Amenorreias e hipogonadismo", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Endometrite", area: "Puerpério", category: 'Ginecologia e Obstetrícia' },
  { name: "Colo curto e parto prematuro", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Cardiotocografia", area: "Vitalidade Fetal", category: 'Ginecologia e Obstetrícia' },
  { name: "Rastreio de câncer de colo de útero – DNA HPV", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Drogas usadas e não usadas na gestação", area: "Farmacologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Maturação cervical – Bishop", area: "Parto", category: 'Ginecologia e Obstetrícia' },
  { name: "Aplicabilidade do fórceps", area: "Parto", category: 'Ginecologia e Obstetrícia' },

  // PEDIATRIA
  { name: "Obstrução intestinal (invaginação, atresias)", area: "Cirurgia Ped", category: 'Pediatria' },
  { name: "Psiquiatria infantil – autismo e TDAH", area: "Geral", category: 'Pediatria' },
  { name: "Toxoplasmose congênita", area: "Neonatologia", category: 'Pediatria' },
  { name: "Púrpura trombocitopênica idiopática", area: "Hematologia", category: 'Pediatria' },
  { name: "Sífilis congênita", area: "Neonatologia", category: 'Pediatria' },
  { name: "Asma infantil", area: "Pneumologia", category: 'Pediatria' },
  { name: "Glomerulonefrites na infância", area: "Nefrologia", category: 'Pediatria' },
  { name: "Diabetes tipo 1 – cetoacidose", area: "Endocrinologia", category: 'Pediatria' },
  { name: "Calendário vacinal", area: "Puericultura", category: 'Pediatria' },
  { name: "Diarreia e manejo da desidratação", area: "Infectologia", category: 'Pediatria' },
  { name: "Leucemias mieloides e linfocíticas", area: "Hematologia/Onco", category: 'Pediatria' },
  { name: "Doença de Kawasaki", area: "Reumatologia", category: 'Pediatria' },
  { name: "Doenças exantemáticas", area: "Infectologia", category: 'Pediatria' },
  { name: "Anemia de Fanconi", area: "Hematologia", category: 'Pediatria' },
  { name: "Reanimação neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "Maus-tratos – bebê sacudido", area: "Geral", category: 'Pediatria' },
  { name: "Classificações do RN (peso, IG)", area: "Neonatologia", category: 'Pediatria' },
  { name: "Icterícia neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "Hemofilias", area: "Hematologia", category: 'Pediatria' },
  { name: "Rinossinusite", area: "Otorrino", category: 'Pediatria' },
  { name: "Artrites infantis", area: "Reumatologia", category: 'Pediatria' },
  { name: "Hipovitaminoses", area: "Puericultura", category: 'Pediatria' },
  { name: "Febre reumática infantil", area: "Reumatologia", category: 'Pediatria' },
  { name: "Malformações da parede abdominal", area: "Cirurgia Ped", category: 'Pediatria' },
  { name: "Testes de triagem neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "Anemias – ferropriva e megaloblástica", area: "Hematologia", category: 'Pediatria' },
  { name: "Doenças do teste do pezinho", area: "Geral", category: 'Pediatria' },
  { name: "Galactosemia", area: "Geral", category: 'Pediatria' },
  { name: "Anafilaxia infantil", area: "Imunologia", category: 'Pediatria' },
  { name: "Investigação de baixa estatura", area: "Endocrinologia", category: 'Pediatria' },
  { name: "Aleitamento materno", area: "Puericultura", category: 'Pediatria' },
  { name: "Mononucleose infecciosa", area: "Infectologia", category: 'Pediatria' },
  { name: "Malária na criança", area: "Infectologia", category: 'Pediatria' },
  { name: "Desenvolvimento sexual – puberdade", area: "Endocrinologia", category: 'Pediatria' },
  { name: "Mastite fúngica", area: "Amamentação", category: 'Pediatria' },
  { name: "Hipoglicemia neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "RN exposto ao HIV", area: "Neonatologia", category: 'Pediatria' },
  { name: "Laringocele e laringomalácea", area: "Otorrino", category: 'Pediatria' },
  { name: "Síndromes respiratórias do RN", area: "Neonatologia", category: 'Pediatria' },
  { name: "BLS/ATLS na criança", area: "Urgência", category: 'Pediatria' },
  { name: "Sobrepeso e obesidade infantil", area: "Puericultura", category: 'Pediatria' },
  { name: "Síndromes: Prader-Willi, Turner, Down, Noonan", area: "Genética", category: 'Pediatria' },
  { name: "Fibrose cística", area: "Pneumologia", category: 'Pediatria' },
  { name: "Verminoses e associações", area: "Infectologia", category: 'Pediatria' },
  { name: "Paralisia obstétrica do plexo braquial", area: "Neonatologia", category: 'Pediatria' },
  { name: "Cardiopatias congênitas", area: "Cardiologia", category: 'Pediatria' },
  { name: "Bebê sibilante", area: "Pneumologia", category: 'Pediatria' },
  { name: "Interssuscepção intestinal", area: "Gastroenterologia", category: 'Pediatria' },
  { name: "Corpo estranho – estridor", area: "Urgência/Otorrino", category: 'Pediatria' },
  { name: "Leishmaniose infantil", area: "Infectologia", category: 'Pediatria' },
  { name: "Neuroblastoma e nefroblastoma", area: "Oncologia", category: 'Pediatria' },
  { name: "Urgências urológicas infantis", area: "Urologia Ped", category: 'Pediatria' },
  { name: "Paralisia de Erb-Duchenne", area: "Ortopedia Ped", category: 'Pediatria' },
  { name: "Celulite pré e pós-septal", area: "Infectologia/Oftalmo", category: 'Pediatria' },
  { name: "Marcos do neurodesenvolvimento", area: "Puericultura", category: 'Pediatria' },
  { name: "Catarata e glaucoma congênito", area: "Oftalmologia", category: 'Pediatria' },

  // MEDICINA PREVENTIVA
  { name: "Níveis de prevenção em saúde", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Atenção domiciliar", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Atributos da atenção primária", area: "APS", category: 'Medicina Preventiva' },
  { name: "Princípios do SUS", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Protocolo SPIKES", area: "Ética/Comunicação", category: 'Medicina Preventiva' },
  { name: "Leis orgânicas 8.080 e 8.142", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Rastreamentos: colo útero, mama, próstata", area: "APS", category: 'Medicina Preventiva' },
  { name: "Doenças de notificação imediata", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "MCCP – método clínico centrado na pessoa", area: "APS", category: 'Medicina Preventiva' },
  { name: "Sinais de prontidão – introdução alimentar", area: "APS", category: 'Medicina Preventiva' },
  { name: "Princípios da atenção primária", area: "APS", category: 'Medicina Preventiva' },
  { name: "Tuberculose latente – investig. e tratam.", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Testes de rastreamento populacional", area: "APS", category: 'Medicina Preventiva' },
  { name: "Estudos epidemiológicos", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "População indígena e ribeirinha", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Instrumentos de abordagem familiar", area: "APS", category: 'Medicina Preventiva' },
  { name: "Calendário vacinal (Preventiva)", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Razão de verossimilhança (LR)", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Atenção psicossocial (RAPS)", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Consultas de pré-natal (APS)", area: "APS", category: 'Medicina Preventiva' },
  { name: "Vertigem na APS: VPPB, Ménière, neurite", area: "APS", category: 'Medicina Preventiva' },
  { name: "Atribuições da equipe da APS", area: "APS", category: 'Medicina Preventiva' },
  { name: "Número necessário a tratar (NNT)", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Participação social no SUS", area: "SUS", category: 'Medicina Preventiva' },
  { name: "HIV – profilaxias (APS)", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Critérios para insulinoterapia (APS)", area: "APS", category: 'Medicina Preventiva' },
  { name: "Desprescrição", area: "APS/Geriatria", category: 'Medicina Preventiva' },
  { name: "Fases do ciclo de vida familiar", area: "APS", category: 'Medicina Preventiva' },
  { name: "SOAP", area: "APS", category: 'Medicina Preventiva' },
  { name: "Atestado de óbito", area: "Ética/Vigilância", category: 'Medicina Preventiva' },
  { name: "Cálculos – tabela 2x2", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Cuidados paliativos (APS)", area: "APS", category: 'Medicina Preventiva' },
  { name: "Composição da ESF e unidades", area: "APS", category: 'Medicina Preventiva' },
  { name: "Escabiose (APS)", area: "APS", category: 'Medicina Preventiva' },
  { name: "Financiamento da APS", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Dengue (Vigilância)", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Risco relativo e risco absoluto", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Estágios de Prochaska e DiClemente", area: "APS", category: 'Medicina Preventiva' },
  { name: "Polifarmácia", area: "APS", category: 'Medicina Preventiva' },
  { name: "Seguimento de sífilis na APS", area: "APS", category: 'Medicina Preventiva' },
  { name: "PNAB", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Violência sexual (Preventiva)", area: "APS", category: 'Medicina Preventiva' },
  { name: "Cuidado do idoso na APS", area: "APS", category: 'Medicina Preventiva' },
  { name: "Modelos flexneriano e dawnsoniano", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Valor preditivo positivo e negativo", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "ITU na gestante (APS)", area: "APS", category: 'Medicina Preventiva' },
  { name: "Testes para tuberculose (APS)", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Programas de rastreio na APS", area: "APS", category: 'Medicina Preventiva' }
];

export const CURRICULUM_DATA: Area[] = [
  {
    id: 'cm',
    name: 'Clínica Médica',
    icon: '🩺',
    color: 'blue',
    topics: [
      { id: 'cm-1', name: 'Glomerulopatias I (síndrome nefrítica, GNRP, alterações assintomáticas)', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-2', name: 'Glomerulopatias II (síndrome nefrótica, glomerulopatias secundárias)', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-3', name: 'Doenças túbulo-intersticiais e vasculares renais', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-4', name: 'Distúrbios hidroeletrolíticos', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-5', name: 'Distúrbios ácido-básicos', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-6', name: 'Insuficiência renal', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-7', name: 'Introdução à reumatologia e artrites', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-8', name: 'Gota', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-9', name: 'Febre reumática', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-10', name: 'Colagenoses I (PM, DM, DMTC, esclerodermia)', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-11', name: 'Colagenoses II (LES, Sjögren)', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-12', name: 'Vasculites', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-13', name: 'Anemias I (ferropriva, doença crônica, megaloblástica)', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-14', name: 'Anemias II (hemolíticas, falciformes, hemoglobinopatias)', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-15', name: 'Leucemias agudas e crônicas', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-16', name: 'Linfomas e mieloma múltiplo', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-17', name: 'Distúrbios da hemostasia', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-18', name: 'Doenças do esôfago', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-19', name: 'Doenças do estômago', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-20', name: 'Hemorragia digestiva alta', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-21', name: 'Síndromes de má-absorção', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-22', name: 'Doença inflamatória intestinal', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-23', name: 'Doença vascular dos intestinos', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-24', name: 'Obstrução intestinal', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-25', name: 'Diverticulose e polipose', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-26', name: 'Câncer de cólon', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-27', name: 'Apendicite aguda', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-28', name: 'Hemorragia digestiva baixa', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-29', name: 'Pancreatite aguda e crônica', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-30', name: 'Câncer de pâncreas', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-31', name: 'Doenças das vias biliares', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-32', name: 'Introdução à hepatologia', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-33', name: 'Hepatites virais', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-34', name: 'Cirrose', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-35', name: 'Complicações da cirrose', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-36', name: 'Hipertensão portal', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-37', name: 'Ascite', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-38', name: 'Encefalopatia hepática', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-39', name: 'Arritmias (taqui e bradiarritmias)', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-40', name: 'Parada cardiorrespiratória', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-41', name: 'Insuficiência cardíaca', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-42', name: 'Hipertensão arterial sistêmica', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-43', name: 'Crise hipertensiva', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-44', name: 'Valvopatias', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-45', name: 'Doença arterial coronariana (IAM e angina)', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-46', name: 'Tireoide I (hipertireoidismo)', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-47', name: 'Tireoide II (tireoidites e câncer)', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-48', name: 'Doenças da suprarrenal', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-49', name: 'Diabetes mellitus', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-50', name: 'Dislipidemia', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-51', name: 'Obesidade', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-52', name: 'Asma', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-53', name: 'DPOC', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-54', name: 'Câncer de pulmão', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-55', name: 'Tromboembolismo pulmonar', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-56', name: 'Tuberculose', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-57', name: 'Pneumonia e complicações', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-58', name: 'AIDS', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-59', name: 'Endocardite infecciosa', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-60', name: 'Meningite', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-61', name: 'Parasitoses intestinais', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-62', name: 'Síndromes febris', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-63', name: 'Síndromes neurológicas', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-64', name: 'AVC', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-65', name: 'Polineuropatias', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-66', name: 'Demências', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-67', name: 'Parkinson', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-68', name: 'Cefaleia', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-69', name: 'Epilepsia', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-70', name: 'Psiquiatria – Parte 1', subArea: 'Psiquiatria', status: StudyStatus.NOT_STARTED },
      { id: 'cm-71', name: 'Psiquiatria – Parte 2', subArea: 'Psiquiatria', status: StudyStatus.NOT_STARTED },
      { id: 'cm-72', name: 'Dermatologia – Parte 1', subArea: 'Dermatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-73', name: 'Dermatologia – Parte 2', subArea: 'Dermatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-74', name: 'Oftalmologia – Parte 1', subArea: 'Oftalmologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-75', name: 'Oftalmologia – Parte 2', subArea: 'Oftalmologia', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'go',
    name: 'Ginecologia e Obstetrícia',
    icon: '🤰',
    color: 'pink',
    topics: [
      { id: 'go-1', name: 'Ciclo menstrual e anticoncepção', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-2', name: 'Amenorreia e ovário policístico', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-3', name: 'Sangramento uterino anormal', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-4', name: 'Endometriose', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-5', name: 'Infertilidade', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-6', name: 'Climatério', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-7', name: 'Distopias genitais', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-8', name: 'Incontinência urinária', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-9', name: 'Doenças das mamas', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-10', name: 'Doenças dos ovários', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-11', name: 'Lesões precursoras do colo uterino', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-12', name: 'Câncer de colo uterino', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-13', name: 'Câncer de endométrio', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-14', name: 'Vulvovaginites', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-15', name: 'IST', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-16', name: 'Cervicites', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-17', name: 'Diagnóstico de gravidez', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-18', name: 'Modificações fisiológicas da gestação', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-19', name: 'Pré-natal', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-20', name: 'Assistência ao parto', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-21', name: 'Parto prematuro', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-22', name: 'Sangramentos da gravidez (1ª e 2ª partes)', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-23', name: 'Doença hemolítica perinatal', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-24', name: 'Distúrbios hipertensivos da gestação', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-25', name: 'Diabetes gestacional', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-26', name: 'Gemelaridade', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-27', name: 'Sofrimento fetal', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-28', name: 'Vitalidade fetal', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-29', name: 'Fórceps', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-30', name: 'Puerpério', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'ped',
    name: 'Pediatria',
    icon: '👶',
    color: 'green',
    topics: [
      { id: 'ped-1', name: 'Neonatologia I', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-2', name: 'Neonatologia II', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-3', name: 'Aleitamento materno', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-4', name: 'Crescimento e desenvolvimento', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-5', name: 'Puberdade', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-6', name: 'Distúrbios do crescimento', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-7', name: 'Desnutrição', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-8', name: 'Baixa estatura', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-9', name: 'Imunização', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-10', name: 'Diarreia aguda e desidratação', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-11', name: 'Infecções respiratórias agudas I', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-12', name: 'Infecções respiratórias agudas II', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-13', name: 'Nefrologia pediátrica', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'ped-14', name: 'Doenças exantemáticas na infância', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'cir',
    name: 'Cirurgia',
    icon: '🏥',
    color: 'red',
    topics: [
      { id: 'cir-1', name: 'Trauma I (primeiro atendimento, cabeça e tórax)', subArea: 'Trauma', status: StudyStatus.NOT_STARTED },
      { id: 'cir-2', name: 'Trauma II (abdome e TCE)', subArea: 'Trauma', status: StudyStatus.NOT_STARTED },
      { id: 'cir-3', name: 'Nefrolitíase', subArea: 'Urologia', status: StudyStatus.NOT_STARTED },
      { id: 'cir-4', name: 'Câncer de próstata', subArea: 'Urologia', status: StudyStatus.NOT_STARTED },
      { id: 'cir-5', name: 'Hyperplasia prostática benigna', subArea: 'Urologia', status: StudyStatus.NOT_STARTED },
      { id: 'cir-6', name: 'REMIT', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cir-7', name: 'Queimaduras', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cir-8', name: 'Hérnias da parede abdominal', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cir-9', name: 'Preparo pré-operatório', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cir-10', name: 'Risco cirúrgico', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cir-11', name: 'Complicações cirúrgicas', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cir-12', name: 'Especialidades cirúrgicas – Parte 1', subArea: 'Especialidades', status: StudyStatus.NOT_STARTED },
      { id: 'cir-13', name: 'Especialidades cirúrgicas – Parte 2', subArea: 'Especialidades', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'pre',
    name: 'Preventiva',
    icon: '🌎',
    color: 'indigo',
    topics: [
      { id: 'pre-1', name: 'Medidas de saúde coletiva', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'pre-2', name: 'Estudos epidemiológicos', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'pre-3', name: 'Epidemiologia clínica', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'pre-4', name: 'Vigilância em saúde', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'pre-5', name: 'Processo epidêmico', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'pre-6', name: 'SUS: evolução histórica', subArea: 'SUS', status: StudyStatus.NOT_STARTED },
      { id: 'pre-7', name: 'Diretrizes do SUS', subArea: 'SUS', status: StudyStatus.NOT_STARTED },
      { id: 'pre-8', name: 'Propostas e Financiamento', subArea: 'SUS', status: StudyStatus.NOT_STARTED },
    ]
  }
];
